project:
  type: website
  output-dir: docs 

website:
  title: "Book"
  navbar:
    left:
      - index.qmd
      - hackatons.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

