project:
  type: website
  output-dir: docs 

website:
  title: "PopSci"
  navbar:
    left:
      - index.qmd
      - hackathons.qmd
      - referencias.qmd 

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

