---
title: "Estudo Orientado: Projetando Hackathons Científicos"
lang: pt-br
slide-format: revealjs
bibliography: references.bib
---

# Sobre o Estudo Orientado

Hackathons são comumente conhecidos como eventos de curta duração nos quais indivíduos ou times competem entre si para tentar resolver um problema proposto pelos organizadores. hackathons tem se popularizado como ferramentas de engajamento na solução de problemas diversos, e o caráter de desafio e competição tende a atrair igualmente participantes experientes e novatos.

Neste estudo orientado os alunos deverão estudar as diferentes modalidades de hackathons, estudando exemplos conhecidos, analisando suas características, mas sob o ponto de vista de **organizadores** de um hackathon.

Alguns dos temas que serão explorados, através de leituras de artigos técnico/científicos, são:

-   Diferentes modelos e aplicações de hackathons.
-   hackathons sobre dados, algoritmos e codificação.
-   Valor potencial de um hackathon.
-   O ciclo de vida de um hackathon.
-   Ferramentas online e offline para hackathons.
-   Divulgação e engajamento.
-   Acompanhamento pós-evento.

As aulas serão exclusivamente online, mas síncronas: não será possível participar das aulas fora do tempo alocado e não serão todas gravadas. Para o [primeiro período de 2024](https://www.gov.br/inpe/pt-br/area-conhecimento/posgraduacao/calendario-academico) o horário proposto é sexta-feira, 8:00 às 10:00, com atividades extras. O estudo dirigido contará como dois créditos.

Como projeto final da disciplina, alunos ou grupos deverão projetar um hackathon considerando todas as fases de sua execução. Projetos serão selecionados para implementação do hackathon em meses posteriores, com apoio da PGCAP e INPE.

Os projetos poderão ser desenvolvidos individualmente ou em duplas. É fortemente recomendado que o aluno (ou membro da dupla) tenha um bom conhecimento do problema, dos dados ou das APIs ou ferramentas a serem utilizadas no hackathon proposto.

É possível consultar participantes externos que possam ajudar na definição dos hackathons, mas a responsabilidade da entrega dos projetos é dos alunos que cursarem a disciplina.

## Alguns temas e projetos de interesse

Para estes temas já temos a coleção de dados definida, e/ou alguma experiência, e/ou algum interesse em promover um hackathon nestes temas, mas outros que atendam aos requisitos da disciplina poderão ser sugeridos.

-   Classificando polígonos em imagens de queimadas (baseado na dissertação de mestrado de Marcelly Homem Coelho).
-   Procurando relações em bases de dados de produção científica (baseado no portal de dados abertos da CAPES).
-   Previsão de dry spells em bacias hidrográficas com machine learning (verificar com pesquisador responsável).
-   Implementação de tarefas de sensoriamento remoto/classificação de imagens/aprendizado de máquina de forma reprodutível por hackathons.

# Cronograma para o primeiro período de 2024

| Dia      | Conteúdo                                                                             |
|----------|--------------------------------------------------------------------------------------|
| 08/03/24 | [Tarefa Pré-Encontros]                                                               |
| 15/03/24 | Tempo para desenvolvimento da primeira tarefa                                        |
| 22/03/24 | [Encontro #1]: Apresentação formal da disciplina e objetivos, definição dos projetos |
| 29/03/24 | [Feriado]{style="color:#ff00A0"}                                                     |
| 05/04/24 | [Encontro #2]:                                                                       |
| 12/04/24 |                                                                                      |
| 19/04/24 |                                                                                      |
| 26/04/24 |                                                                                      |
| 03/05/24 |                                                                                      |
| 10/05/24 |                                                                                      |
| 17/05/24 |                                                                                      |
| 24/05/24 |                                                                                      |

: {tbl-colwidths="\[20,80\]" .striped .hover}

Veja também o [calendário acadêmico](https://www.gov.br/inpe/pt-br/area-conhecimento/posgraduacao/calendario-academico) de 2024.

# Tarefa Pré-Encontros

Nesta disciplina vamos estudar **hackathons**, em particular como planejar e implementar um hackathon de sucesso. Para isto é importante entender alguns aspectos e pensar em projetos para desenvolver durante a disciplina.

Antes de termos nosso primeiro encontro presencial sugiro que considerem uma das tarefas preliminares inicias a seguir:

1.  Visite o site [Hackathon Planning Kit](https://hackathon-planning-kit.org/). O que eles oferecem? Qual é o custo? Quais são os requisitos para usar as ideias/material/abordagem/etc?
2.  Existem muitas plataformas para ciência de dados online que podem ser usadas para hackathons baseados em dados. Quais são as vantagens e desvantagens delas? Considerando o [Kaggle](https://www.kaggle.com/) como sendo um padrão, quais são os diferenciais das alternativas? Considere custos, flexibilidade, limitações em uso de CPU/Dados, privacidade dos dados, etc. Use o [Relatório do Ebenezer Agyei-Yeboah](Resources/RelatórioPCI.pdf) como base ou inspiração.
3.  Veja a revisão sistemática em [@medina2020we] ([link](Resources/Medina2020.pdf)). Quais são as principais conclusões? Podemos expandir ou especializar esta revisão sistemática? Que outras *research questions* podem ser interessantes?
4.  Leia o artigo [@nolte2020happens] ([link](Resources/Nolte2020.pdf)). Como os autores identificam projetos com continuidade?

Escolham uma (ou mais) destas referências para estudar e preparem um relatório *simples* (sugestão: apresentação em 4-5 slides) para a nossa primeira reunião. O trabalho pode ser feito em duplas se assim quiserem.

```{=html}
<!--
 Veja o video [Mini-curso: Bibliometria na prática com R e Bibliometrix](https://youtu.be/2XKsq_y9z_M)\] por Clayton Martins Pereira, que ensina como fazer uma análise bibliométrica a partir de palavras-chaves. 
 -->
```
# Encontro #1

(ainda em preparo!)

```{=html}
<iframe class="slide-deck" src="Hackathons-Aula01/"></iframe>
```
[Clique aqui para abrir em nova janela](Hackathons-Aula01/){target="_blank"}

# Encontro #2

# Bibliografia
